Repository cyclops-operation/switter, pull requests merged in 2023-10, with the labels that each got.

#35 fix(global): theme-toggle 수정 및 sheet 태그구조 변경
  app/(auth)/feed/page.tsx
  app/(auth)/src/ui/sheet/comment-sheet.tsx
  components/common/meteor-effect.tsx
  components/common/theme-toggle.tsx
Labels: 🔥 Hotfix

#37 feat(request): 요청사항 전달 기능 프로토타입 추가
  app/(auth)/layout.tsx
  app/(auth)/src/ui/layout/request-dialog.tsx
  app/api/sheet/action.ts
  app/api/sheet/route.ts
  components/common/icons.tsx
  interface/sheet.ts
  lib/api-route.ts
  lib/error-message.ts
  package.json
  yarn.lock
Labels: 🎯 Feature

#38 feat(feed): 피드 검색기능 추가
  app/(auth)/feed/page.tsx
  app/(auth)/src/hooks/useCommentList.ts
  app/(auth)/src/hooks/useFeedList.ts
  app/(auth)/src/ui/dialog/comment-dialog.tsx
  app/(auth)/src/ui/dialog/feed-dialog.tsx
  app/(auth)/src/ui/dialog/monster-search-dialog.tsx
  app/(auth)/src/ui/list/feed-list.tsx
  app/(auth)/src/ui/search/feed-search.tsx
  app/api/feed/route.ts
  components/common/icons.tsx
  interface/feed.ts
Labels: 🎯 Feature, 🔥 Hotfix

#39 fix(auth): 로그인, 회원가입, 유저관리 로직 수정
  app/(account)/layout.tsx
  app/(account)/sign-in/page.tsx
  app/(account)/sign-in/src/ui/sign-in-form.tsx
  app/(account)/sign-up/page.tsx
  app/(account)/sign-up/src/ui/sign-up-form.tsx
  app/(account)/src/ui/header.tsx
  app/(account)/waiting/page.tsx
  app/(account)/waiting/src/ui/form/create.tsx
  app/(account)/waiting/src/ui/form/edit.tsx
  app/(account)/waiting/src/ui/form/index.tsx
  app/(account)/waiting/src/ui/pending.tsx
  app/(auth)/admin/layout.tsx
  app/(auth)/admin/page.tsx
  app/(auth)/admin/src/ui/role-select.tsx
  app/(auth)/layout.tsx
  app/(auth)/src/ui/layout/request-dialog.tsx
  app/(auth)/src/ui/layout/root-pusher.tsx
  app/(auth)/src/ui/layout/site-header/index.tsx
  app/(auth)/src/ui/layout/site-header/sign-out-button.tsx
  app/(auth)/src/ui/list/feed-list.tsx
  app/(auth)/src/ui/sheet/comment-sheet.tsx
  app/api/account/route.ts
  app/api/auth/[...nextauth]/route.ts
  app/api/me/route.ts
  app/api/sheet/route.ts
  app/api/user/route.ts
  components/common/icons.tsx
  components/common/social-login.tsx
  config/site.ts
  interface/account.ts
  interface/user.ts
  lib/api-route.ts
  lib/error-message.ts
  lib/page-route.ts
  next.config.mjs
  package.json
  prisma/schema.prisma
  yarn.lock
Labels: 🔥 Hotfix

#40 chore: Release as 1.0.1
  app/(account)/layout.tsx
  app/(account)/sign-in/page.tsx
  app/(account)/sign-in/src/ui/sign-in-form.tsx
  app/(account)/sign-up/page.tsx
  app/(account)/sign-up/src/ui/sign-up-form.tsx
  app/(account)/src/ui/header.tsx
  app/(account)/waiting/page.tsx
  app/(account)/waiting/src/ui/form/create.tsx
  app/(account)/waiting/src/ui/form/edit.tsx
  app/(account)/waiting/src/ui/form/index.tsx
  app/(account)/waiting/src/ui/pending.tsx
  app/(auth)/admin/layout.tsx
  app/(auth)/admin/page.tsx
  app/(auth)/admin/src/ui/role-select.tsx
  app/(auth)/feed/page.tsx
  app/(auth)/layout.tsx
  app/(auth)/src/hooks/useCommentList.ts
  app/(auth)/src/hooks/useFeedList.ts
  app/(auth)/src/ui/dialog/comment-dialog.tsx
  app/(auth)/src/ui/dialog/feed-dialog.tsx
  app/(auth)/src/ui/dialog/monster-search-dialog.tsx
  app/(auth)/src/ui/layout/request-dialog.tsx
  app/(auth)/src/ui/layout/root-pusher.tsx
  app/(auth)/src/ui/layout/site-header/index.tsx
  app/(auth)/src/ui/layout/site-header/sign-out-button.tsx
  app/(auth)/src/ui/list/feed-list.tsx
  app/(auth)/src/ui/search/feed-search.tsx
  app/(auth)/src/ui/sheet/comment-sheet.tsx
  app/api/account/route.ts
  app/api/auth/[...nextauth]/route.ts
  app/api/feed/route.ts
  app/api/me/route.ts
  app/api/sheet/route.ts
  app/api/user/route.ts
  components/common/icons.tsx
  components/common/social-login.tsx
  config/site.ts
  interface/account.ts
  interface/feed.ts
  interface/user.ts
  lib/api-route.ts
  lib/error-message.ts
  lib/page-route.ts
  next.config.mjs
  package.json
  prisma/schema.prisma
  yarn.lock
Labels: 🚀 Deploy

#42 fix(auth): [hotfix] 로그인 로직 로딩조건 추가
  app/(account)/sign-in/src/ui/sign-in-form.tsx
  app/(auth)/src/ui/layout/request-dialog.tsx
Labels: 🔥 Hotfix

#49 fix(feed): 피드, 코맨트 키워드 입력조건 수정
  app/(auth)/src/ui/dialog/comment-dialog.tsx
  app/(auth)/src/ui/dialog/feed-dialog.tsx
  app/(auth)/src/ui/sheet/comment-sheet.tsx
  app/api/comment/route.ts
  interface/comment.ts
  interface/feed.ts
  lib/error-message.ts
Labels: 📝 Fix

#52 fix(create): 피드, 코멘트 생성시 중복체크 및 에러핸들러 추가
  app/(auth)/feed/page.tsx
  app/(auth)/src/ui/dialog/comment-dialog.tsx
  app/(auth)/src/ui/dialog/feed-dialog.tsx
  app/api/action.ts
  app/api/comment/route.ts
  app/api/feed/route.ts
  app/api/me/route.ts
  app/api/monster/route.ts
  app/api/notification/route.ts
  app/api/sheet/route.ts
  app/api/user/route.ts
  lib/error-message.ts
  package.json
  yarn.lock
Labels: 📝 Fix

#55 fix: MVP 배포 이후 자체 QA
  app/(account)/layout.tsx
  app/(account)/sign-in/src/ui/sign-in-form.tsx
  app/(auth)/src/hooks/useCommentDelete.ts
  app/(auth)/src/hooks/useFeedDelete.ts
  app/(auth)/src/hooks/useFeedList.ts
  app/(auth)/src/ui/dialog/comment-dialog.tsx
  app/(auth)/src/ui/list/feed-list.tsx
  app/api/sheet/action.ts
  app/api/sheet/route.ts
  components/common/loading/full-page.tsx
  components/common/loading/index.tsx
  lib/airtable.ts
  lib/api-route.ts
  lib/page-route.ts
  lib/utils.ts
  package.json
  yarn.lock
Labels: 📝 Fix

#56 chore(release): 1.0.5 배포 🎉
  .github/workflows/deploy.yml
  .github/workflows/release-deploy.yml
  app/(account)/layout.tsx
  app/(account)/sign-in/src/ui/sign-in-form.tsx
  app/(auth)/src/hooks/useCommentDelete.ts
  app/(auth)/src/hooks/useFeedDelete.ts
  app/(auth)/src/hooks/useFeedList.ts
  app/(auth)/src/ui/dialog/comment-dialog.tsx
  app/(auth)/src/ui/list/feed-list.tsx
  app/api/sheet/action.ts
  app/api/sheet/route.ts
  components/common/loading/full-page.tsx
  components/common/loading/index.tsx
  lib/airtable.ts
  lib/api-route.ts
  lib/page-route.ts
  lib/utils.ts
  next.config.mjs
  package.json
  yarn.lock
Labels: 🚀 Deploy

#59 refactor(UX): 덱 추가 및 제거 로딩 설정 및 toast 추가
  app/(auth)/admin/src/ui/role-select.tsx
  app/(auth)/src/hooks/useCommentDelete.ts
  app/(auth)/src/hooks/useFeedDelete.ts
  app/(auth)/src/ui/dialog/comment-dialog.tsx
  app/(auth)/src/ui/dialog/feed-dialog.tsx
  app/(auth)/src/ui/sheet/comment-sheet.tsx
Labels: 🛠 Refactor

#69 feat: 관리자 몬스터 관리 기능 추가
  app/(account)/waiting/src/ui/pending.tsx
  app/(auth)/admin/layout.tsx
  app/(auth)/admin/monster/page.tsx
  app/(auth)/admin/monster/src/ui/add-monster-dialog.tsx
  app/(auth)/admin/monster/src/ui/monster-table.tsx
  app/(auth)/admin/request/page.tsx
  app/(auth)/src/hooks/useMonsterList.ts
  app/(auth)/src/ui/card/comment-card.tsx
  app/(auth)/src/ui/card/feed-card.tsx
  app/(auth)/src/ui/dialog/monster-manage-dialog.tsx
  app/(auth)/src/ui/dialog/monster-search-dialog.tsx
  app/(auth)/src/ui/layout/main-nav.tsx
  app/(auth)/src/ui/layout/main-nav/index.tsx
  app/(auth)/src/ui/layout/main-nav/route-menu.tsx
  app/(auth)/src/ui/layout/site-header/index.tsx
  app/(auth)/src/ui/list/feed-list.tsx
  app/(auth)/src/ui/sheet/comment-sheet.tsx
  app/api/action.ts
  app/api/comment/route.ts
  app/api/feed/route.ts
  app/api/monster/route.ts
  components/common/icons.tsx
  components/common/loading/index.tsx
  components/common/pagination.tsx
  components/common/tag.tsx
  components/ui/navigation-menu.tsx
  config/site.ts
  hook/useDebounceState.ts
  interface/comment.ts
  interface/common.ts
  interface/feed.ts
  interface/monster.ts
  interface/nav.ts
  interface/notification.ts
  lib/animation.ts
  lib/error-message.ts
  lib/page-route.ts
  lib/utils.ts
  package.json
  yarn.lock
Labels: 🎯 Feature

#66 chore(release): 1.1.0 버전 배포 🎉
  app/(account)/waiting/src/ui/pending.tsx
  app/(auth)/admin/layout.tsx
  app/(auth)/admin/monster/page.tsx
  app/(auth)/admin/monster/src/ui/add-monster-dialog.tsx
  app/(auth)/admin/monster/src/ui/monster-table.tsx
  app/(auth)/admin/request/page.tsx
  app/(auth)/admin/src/ui/role-select.tsx
  app/(auth)/src/hooks/useCommentDelete.ts
  app/(auth)/src/hooks/useCommentList.ts
  app/(auth)/src/hooks/useFeedDelete.ts
  app/(auth)/src/hooks/useFeedList.ts
  app/(auth)/src/hooks/useFeedSearchParams.ts
  app/(auth)/src/hooks/useMonsterList.ts
  app/(auth)/src/ui/card/comment-card.tsx
  app/(auth)/src/ui/card/feed-card.tsx
  app/(auth)/src/ui/dialog/comment-dialog.tsx
  app/(auth)/src/ui/dialog/delete-dialog.tsx
  app/(auth)/src/ui/dialog/feed-dialog.tsx
  app/(auth)/src/ui/dialog/monster-manage-dialog.tsx
  app/(auth)/src/ui/dialog/monster-search-dialog.tsx
  app/(auth)/src/ui/layout/main-nav.tsx
  app/(auth)/src/ui/layout/main-nav/index.tsx
  app/(auth)/src/ui/layout/main-nav/route-menu.tsx
  app/(auth)/src/ui/layout/site-header/index.tsx
  app/(auth)/src/ui/list/feed-list.tsx
  app/(auth)/src/ui/sheet/comment-sheet.tsx
  app/api/action.ts
  app/api/comment/route.ts
  app/api/feed/route.ts
  app/api/monster/route.ts
  components/common/icons.tsx
  components/common/loading/index.tsx
  components/common/pagination.tsx
  components/common/tag.tsx
  components/ui/navigation-menu.tsx
  config/site.ts
  hook/useDebounceState.ts
  interface/comment.ts
  interface/common.ts
  interface/feed.ts
  interface/monster.ts
  interface/nav.ts
  interface/notification.ts
  lib/animation.ts
  lib/error-message.ts
  lib/page-route.ts
  lib/utils.ts
  package.json
  yarn.lock
Labels: 🚀 Deploy

#72 fix(comment): comment 내부 description 기능 추가
  app/(auth)/admin/monster/src/ui/monster-table.tsx
  app/(auth)/src/hooks/useCommentDescription.ts
  app/(auth)/src/ui/card/comment-card.tsx
  app/(auth)/src/ui/card/feed-card.tsx
  app/(auth)/src/ui/dialog/comment-dialog.tsx
  app/(auth)/src/ui/dialog/delete-dialog.tsx
  app/(auth)/src/ui/dialog/monster-manage-dialog.tsx
  app/(auth)/src/ui/sheet/comment-sheet.tsx
  app/api/comment/description/route.ts
  app/api/comment/route.ts
  components/ui/hover-card.tsx
  interface/comment.ts
  lib/api-route.ts
  package.json
  prisma/schema.prisma
  yarn.lock
Labels: 🎯 Feature, 🔥 Hotfix

#73 chore: 1.0.6 hotfix2 배포 🔥
  app/(auth)/admin/monster/src/ui/monster-table.tsx
  app/(auth)/src/hooks/useCommentDescription.ts
  app/(auth)/src/ui/card/comment-card.tsx
  app/(auth)/src/ui/card/feed-card.tsx
  app/(auth)/src/ui/dialog/comment-dialog.tsx
  app/(auth)/src/ui/dialog/delete-dialog.tsx
  app/(auth)/src/ui/dialog/monster-manage-dialog.tsx
  app/(auth)/src/ui/sheet/comment-sheet.tsx
  app/api/comment/description/route.ts
  app/api/comment/route.ts
  components/ui/hover-card.tsx
  interface/comment.ts
  lib/api-route.ts
  package.json
  prisma/schema.prisma
  yarn.lock
Labels: 🚀 Deploy

#78 refactor(account): `(account)` 세그먼트 반응형 반영
  app/(account)/layout.tsx
  app/(account)/sign-in/page.tsx
  app/(account)/sign-up/page.tsx
  app/(account)/src/ui/footer-link.tsx
  app/(account)/src/ui/header.tsx
  app/(account)/waiting/page.tsx
  app/(account)/waiting/src/ui/other-account-button.tsx
Labels: 👻 BugFix, ➕ Improvement

#77 fix(type-error): 비동기 서버 컴포넌트 `import` 오류
  app/(account)/waiting/page.tsx
  app/(auth)/src/ui/layout/site-header/index.tsx
  package.json
  yarn.lock
Labels: 👻 BugFix

#81 fix: 피드 모바일 반응형 반영
  app/(auth)/src/ui/card/comment-card.tsx
  app/(auth)/src/ui/list/feed-list.tsx
  app/(auth)/src/ui/sheet/comment-sheet.tsx
  components/common/icons.tsx
  tailwind.config.js
Labels: 📝 Fix, ➕ Improvement

#82 feat(navigation): navigation 반응형 스타일 추가 및 어드민 페이지 반응형 스타일 수정
  app/(auth)/admin/monster/page.tsx
  app/(auth)/admin/monster/src/ui/monster-table.tsx
  app/(auth)/admin/request/page.tsx
  app/(auth)/src/ui/layout/main-nav/route-menu.tsx
  app/(auth)/src/ui/layout/site-header/index.tsx
  app/(auth)/src/ui/layout/site-header/main-menu.tsx
  app/(auth)/src/ui/layout/site-header/mobile-menu-sheet.tsx
  app/(auth)/src/ui/layout/site-header/sign-out-button.tsx
  components/common/icons.tsx
Labels: 🎯 Feature, 🎨 Style

#80 chore: 1.0.7 버전 배포 🎉
  app/(account)/layout.tsx
  app/(account)/sign-in/page.tsx
  app/(account)/sign-up/page.tsx
  app/(account)/src/ui/footer-link.tsx
  app/(account)/src/ui/header.tsx
  app/(account)/waiting/page.tsx
  app/(account)/waiting/src/ui/other-account-button.tsx
  app/(auth)/admin/monster/page.tsx
  app/(auth)/admin/monster/src/ui/monster-table.tsx
  app/(auth)/admin/request/page.tsx
  app/(auth)/src/ui/card/comment-card.tsx
  app/(auth)/src/ui/layout/main-nav/route-menu.tsx
  app/(auth)/src/ui/layout/site-header/index.tsx
  app/(auth)/src/ui/layout/site-header/main-menu.tsx
  app/(auth)/src/ui/layout/site-header/mobile-menu-sheet.tsx
  app/(auth)/src/ui/layout/site-header/sign-out-button.tsx
  app/(auth)/src/ui/list/feed-list.tsx
  app/(auth)/src/ui/sheet/comment-sheet.tsx
  components/common/icons.tsx
  package.json
  tailwind.config.js
  yarn.lock
Labels: 🚀 Deploy

#84 chore: 1.0.7 Hotfix1 배포 🔥
  app/(auth)/src/ui/layout/request-dialog.tsx
  components/ui/alert-dialog.tsx
  components/ui/dialog.tsx
Labels: 🔥 Hotfix

#87 feat(deploy): sbk 서버 추가
  .github/workflows/sbk-deploy.yml
Labels: 🚀 Deploy
