Repository cyclops-operation/switter, pull requests merged in 2023-09, with the labels that each got.

#1 setting(release-please): CHANGELOG 업데이트 워크플로우 추가
  .github/workflows/changelog.yml
Labels: ⚙ Setting

#3 fix(setting): Deploy Action workname, PR Template 수정
  .github/pull_request_template.md
  .github/workflows/deploy.yml
  .vscode/settings.json
Labels: 🚀 Deploy, 📚 Docs

#4 feat(component): shadcn/ui 컴포넌트 추가
  app/layout.tsx
  components/common/icons.tsx
  components/common/tailwind-indicator.tsx
  components/common/theme-toggle.tsx
  components/layout/main-nav.tsx
  components/layout/site-header.tsx
  components/ui/button.tsx
  components/ui/card.tsx
  components/ui/checkbox.tsx
  components/ui/dialog.tsx
  components/ui/dropdown-menu.tsx
  components/ui/form.tsx
  components/ui/input.tsx
  components/ui/label.tsx
  components/ui/radio-group.tsx
  components/ui/scroll-area.tsx
  components/ui/select.tsx
  components/ui/separator.tsx
  components/ui/sheet.tsx
  components/ui/skeleton.tsx
  components/ui/switch.tsx
  components/ui/tabs.tsx
  components/ui/textarea.tsx
  components/ui/toast.tsx
  components/ui/toaster.tsx
  components/ui/toggle.tsx
  components/ui/tooltip.tsx
  components/ui/use-toast.ts
  package.json
  prettier.config.js
  theme/theme-provider.tsx
  tsconfig.json
  yarn.lock
Labels: 📍 Chore

#5 feat(setting): release deploy yml 추가
  .github/workflows/release-deploy.yml
Labels: 🚀 Deploy

#7 setting(telegram): 텔레그램 알림 추가
  .github/workflows/pr-created.yml
  .github/workflows/pr-review.yml
Labels: ⚙ Setting

#11 feat(monster): 데이터 가공을 위한 임시 몬스터리스트 로직 추가
  app/(auth)/feed/page.tsx
  app/api/monster/route.ts
  app/api/route.ts
  app/layout.tsx
  components/common/icons.tsx
  components/common/monster-image.tsx
  components/layout/main-nav.tsx
  components/monster-dialog.tsx
  components/ui/popover.tsx
  interface/monster.ts
  interface/nav.ts
  lib/monster.ts
  lib/pusher.ts
  package.json
  prisma/schema.prisma
  providers/query-provider.tsx
  public/images/img_elements_dark.png
  public/images/img_elements_fire.png
  public/images/img_elements_light.png
  public/images/img_elements_water.png
  public/images/img_elements_wind.png
  styles/monster.css
  types/nav.ts
  yarn.lock
Labels: 🎯 Feature, 🔥 Hotfix

#12 fix(monster): 몬스터 수정 인풋 공백입력 방지 로직 추가
  components/common/monster-image.tsx
  providers/query-provider.tsx
Labels: 🎯 Feature, 👻 BugFix

#13 fix(monster): 몬스터 검색인풋 추가, Framer-Motion 테스트 로직 추가
  app/(auth)/feed/page.tsx
  app/(public)/docs/page.tsx
  app/layout.tsx
  components/common/monster-image.tsx
  components/monster-dialog.tsx
  lib/utils.ts
  package.json
  yarn.lock
Labels: 📍 Chore, 🛠 Refactor, 🎯 Feature

#14 fix(monster): 몬스터 영문검색 조건 수정
  components/monster-dialog.tsx
Labels: 👻 BugFix

#10 feat(setting): commit lint 추가
  .github/pull_request_template.md
  .husky/commit-msg
  .vscode/settings.json
  commitlint.config.js
  package.json
  yarn.lock
Labels: ⚙ Setting

#17 style(layout): 루트 레이아웃 세그먼트 별로 분리
  app/(auth)/layout.tsx
  app/layout.tsx
Labels: 🎨 Style

#18 fix(monster): 몬스터 정보 저장 후 Popover가 닫히는 로직 추가
  components/common/monster-image.tsx
Labels: 🔥 Hotfix

#21 fix(setting): prisma client 다중연결 오류수정
  app/api/monster/route.ts
  app/api/route.ts
  lib/prisma.ts
Labels: 🔥 Hotfix

#23 feat(feed): 피드 생성 Dialog 추가
  app/(account)/waiting/src/ui/form/index.tsx
  app/(auth)/feed/page.tsx
  components/common/icons.tsx
  components/common/monster-image.tsx
  components/feed/feed-aisde.tsx
  components/feed/feed-dialog.tsx
  components/feed/monster-dialog.tsx
  components/feed/monster-search-dialog.tsx
  components/feed/pusher-dialog.tsx
  components/ui/command.tsx
  interface/monster.ts
  lib/api-route.ts
  lib/error-message.ts
  lib/monster.ts
  package.json
  yarn.lock
Labels: 📍 Chore, 🎯 Feature

#25 feat: 로그아웃 프로세스 추가
  app/(account)/waiting/page.tsx
  app/(account)/waiting/src/ui/form/create.tsx
  app/(account)/waiting/src/ui/form/edit.tsx
  app/(account)/waiting/src/ui/form/index.tsx
  app/(auth)/layout.tsx
  app/api/account/action.ts
  app/page.tsx
  components/common/social-login.tsx
  components/layout/site-header.tsx
Labels: 🎯 Feature

#27 feat: 가입 요청 관리 페이지 추가
  app/(auth)/admin/layout.tsx
  app/(auth)/admin/page.tsx
  app/(auth)/admin/src/ui/role-select.tsx
  app/api/user/action.ts
  app/api/user/route.ts
  components/common/content-header.tsx
  components/ui/table.tsx
  config/site.ts
  lib/api-route.ts
  lib/page-route.ts
  next.config.mjs
Labels: 🎯 Feature

#30 feat(feed): next-auth session type 수정
  app/(account)/layout.tsx
  app/(account)/waiting/page.tsx
  app/(auth)/AuthLayout.tsx
  app/(auth)/admin/layout.tsx
  app/(auth)/layout.tsx
  app/api/account/action.ts
  app/api/account/route.ts
  app/api/auth/[...nextauth]/route.ts
  app/api/user/route.ts
  interface/next-auth.d.ts
  lib/utils.ts
Labels: 🛠 Refactor

#31 feat: 알림 기능 추가
  app/(account)/waiting/src/ui/pending.tsx
  app/(auth)/AuthLayout.tsx
  app/(auth)/layout.tsx
  app/api/alarm/[id]/route.ts
  app/api/alarm/action.ts
  app/api/alarm/admin/route.ts
  app/api/alarm/route.ts
  components/common/icons.tsx
  components/layout/root-pusher.tsx
  components/layout/site-header.tsx
  components/layout/site-header/index.tsx
  components/layout/site-header/side-alarm.tsx
  components/layout/site-header/sign-out-button.tsx
  interface/alarm.ts
  interface/common.ts
  lib/api-route.ts
  lib/pusher.ts
  prisma/schema.prisma
Labels: 🎯 Feature
